//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace AcikBakkal.Module.BusinessObjects.Biz
{

    public partial class Category : XPObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        Category fParent;
        [Association(@"CategoryReferencesCategory")]
        public Category Parent
        {
            get { return fParent; }
            set { SetPropertyValue<Category>(nameof(Parent), ref fParent, value); }
        }
        [Association(@"CategoryReferencesCategory")]
        public XPCollection<Category> CategoryCollection { get { return GetCollection<Category>(nameof(CategoryCollection)); } }
    }

}
