//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace AcikBakkal.Module.BusinessObjects.Biz
{

    public partial class Customer : XPObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fSurname;
        public string Surname
        {
            get { return fSurname; }
            set { SetPropertyValue<string>(nameof(Surname), ref fSurname, value); }
        }
        DateTime fBirthdate;
        public DateTime Birthdate
        {
            get { return fBirthdate; }
            set { SetPropertyValue<DateTime>(nameof(Birthdate), ref fBirthdate, value); }
        }
        AcikBakkal.Module.BusinessObjects.BizCode.EGender fGender;
        public AcikBakkal.Module.BusinessObjects.BizCode.EGender Gender
        {
            get { return fGender; }
            set { SetPropertyValue<AcikBakkal.Module.BusinessObjects.BizCode.EGender>(nameof(Gender), ref fGender, value); }
        }
        string fPhone;
        public string Phone
        {
            get { return fPhone; }
            set { SetPropertyValue<string>(nameof(Phone), ref fPhone, value); }
        }
        string fEmail;
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>(nameof(Email), ref fEmail, value); }
        }
        string fNotificationToken;
        public string NotificationToken
        {
            get { return fNotificationToken; }
            set { SetPropertyValue<string>(nameof(NotificationToken), ref fNotificationToken, value); }
        }
        [Association(@"OrderReferencesCustomer")]
        public XPCollection<Order> Orders { get { return GetCollection<Order>(nameof(Orders)); } }
    }

}
