//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace AcikBakkal.Module.BusinessObjects.Biz
{

    public partial class OrderDetail : XPObject
    {
        Order fOrder;
        [Association(@"OrderDetailReferencesOrder")]
        public Order Order
        {
            get { return fOrder; }
            set { SetPropertyValue<Order>(nameof(Order), ref fOrder, value); }
        }
        string fShopProduct;
        public string ShopProduct
        {
            get { return fShopProduct; }
            set { SetPropertyValue<string>(nameof(ShopProduct), ref fShopProduct, value); }
        }
        decimal fPrice;
        public decimal Price
        {
            get { return fPrice; }
            set { SetPropertyValue<decimal>(nameof(Price), ref fPrice, value); }
        }
        decimal fAmount;
        public decimal Amount
        {
            get { return fAmount; }
            set { SetPropertyValue<decimal>(nameof(Amount), ref fAmount, value); }
        }
        string fNote;
        public string Note
        {
            get { return fNote; }
            set { SetPropertyValue<string>(nameof(Note), ref fNote, value); }
        }
    }

}
