//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace AcikBakkal.Module.BusinessObjects.Biz
{

    public partial class Shop : XPObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fPhone;
        public string Phone
        {
            get { return fPhone; }
            set { SetPropertyValue<string>(nameof(Phone), ref fPhone, value); }
        }
        string fEmail;
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>(nameof(Email), ref fEmail, value); }
        }
        string fNotificationToken;
        public string NotificationToken
        {
            get { return fNotificationToken; }
            set { SetPropertyValue<string>(nameof(NotificationToken), ref fNotificationToken, value); }
        }
        string fClient;
        public string Client
        {
            get { return fClient; }
            set { SetPropertyValue<string>(nameof(Client), ref fClient, value); }
        }
        [Association(@"ShopProductReferencesShop")]
        public XPCollection<ShopProduct> ShopProducts { get { return GetCollection<ShopProduct>(nameof(ShopProducts)); } }
        [Association(@"OrderReferencesShop")]
        public XPCollection<Order> Orders { get { return GetCollection<Order>(nameof(Orders)); } }
    }

}
